### PR TITLE
NCC Group tech test feedback

### PR DESCRIPTION
**Pull request by MalcolmSmithUK**
Hi Paul,

I'm acting courtesy of Jamie Coombs at NCC Group, I'm a Senior Web Applications Developer here.  He asked me to add some feedback to your tech so you could see what could have been improved.

Hopefully the format is OK and readable, I couldn't seem to create notes on work that was already merged!  Each commit relates to an area of note - I've also added one as a general summary.  Hope you find it of value.

Please direct any further questions to your usual contact/agency.

Kind regards,
Malcolm Smith

### CODE REVIEW

**Comment by levexis** [comment]
Thanks, appreciate your comments. Would be interested to see what the better solutions if you have time to paste in examples. Tests are running in circle CI but am more interested in your comments regarding better ways to detect elements etc. Regards, Paul.

**Comment by MalcolmSmithUK** [comment]
Likewise, the fact that the tests didn't run wasn't important.  It was good to see you'd bothered writing them at all! :)

With regards to the elements - the majority operations in your unit tests were string based. This was often through multiple contains assertions to test the same element, but with no way of telling they were present on the same element, or telling whether they were an element at all.  The innerHtml is also at the mercy of directives contained within which is far beyond the scope of a unit and not what is being tested.  Think about how Angular interfaces with jQuery, and remember that you can leverage the build of controllers, directives etc before each assertion with different scopes.

You may also wish to place less emphasis on testing your templates.  If you're using angular templating and your unit test is assuring state and methods, then you just end up testing angular itself.  The e2e tests should guarantee that interface for given behaviours is available and usable.

I won't be able to paste any examples I'm afraid, but again I hope this is helpful.  It was a comprehensive test, just missed experience with these particular technologies.  Good luck!

**Comment by levexis** [comment]
:) I didn't realise I was supposed to be iterating my test code or I wouldn't have asked! Am doing that now...

BTW I did some tests into script placement and found that it doesn't matter where you put the scripts. This is an area that I know fairly well but I wanted to double check things haven't changed - http://www.slideshare.net/TagManInc/smart-tag-loading-script-loading-case-study-2011.

Placing scripts in the head should not adversely effect load speed and, as Angular is responsible for loading dependencies, it should arguably be the first thing in the head. I added some nodeJS code to the project that would delay a script downloading and ran it in all the main browsers -you can see from crossbrowsertesting.com that it seems to make no difference in modern browsers….

2 in the head and 2 in the body - http://app.crossbrowsertesting.com/public/i01bee863c4fd274/screenshots/z4d9e5aa4eb2149ab10d
4 in the body - http://app.crossbrowsertesting.com/public/i01bee863c4fd274/screenshots/zcb5dd525a29df69e01a

Script loading did used to be a much bigger problem but browsers have come on quite a bit since Steve Souder’s original research. Let me know if I've missed the point on that, thanks!

**Comment by levexis** [comment]
I've implemented changes on feedback branch and will create a pull request for that + add you

**Pull request closed without merging**
